# version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - wordpress
      - certbot  # 让 certbot 在 nginx 之前运行
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=${DOMAIN}
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
      - ./ssl:/etc/nginx/ssl  # SSL 证书存储路径
      - ./:/var/www/html

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - ./:/var/www/html

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./backups:/backups
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    depends_on:
      - nginx
    volumes:
      - ./ssl:/etc/letsencrypt  # 存储 SSL 证书
      - ./ssl/www:/var/www/certbot  # ACME 认证目录
